<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="AWSSDK.S3" />
        <PackageReference Include="Cronos" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core.BackgroundJobs\Core.BackgroundJobs.csproj" />
        <ProjectReference Include="..\Core.DateTimeProvider\Core.DateTimeProvider.csproj" />
        <ProjectReference Include="..\Core.DomainTypes\Core.DomainTypes.csproj" />
        <ProjectReference Include="..\Core.Extensions\Core.Extensions.csproj" />
        <ProjectReference Include="..\Core.Logger\Core.Logger.csproj" />
        <ProjectReference Include="..\Core.RequestContext\Core.RequestContext.csproj" />
        <ProjectReference Include="..\Core.ResultPattern\Core.ResultPattern.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Core.InfrastructureTests.Storage" />
    </ItemGroup>

</Project>