<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>false</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit" />
        <PackageReference Include="Testcontainers.Keycloak" />
        <PackageReference Include="Testcontainers.PostgreSql" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Newtonsoft.Json" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Core.CQRS.Decorators\Core.CQRS.Decorators.csproj" />
        <ProjectReference Include="..\..\src\Core.Identity\Core.Identity.csproj" />
        <ProjectReference Include="..\..\src\Core.DateTimeProvider\Core.DateTimeProvider.csproj" />
        <ProjectReference Include="..\..\src\Core.Keycloak\Core.Keycloak.csproj" />
        <ProjectReference Include="..\..\src\Core.KeycloakSync\Core.KeycloakSync.csproj" />
        <ProjectReference Include="..\..\src\Core.Outbox\Core.Outbox.csproj" />
        <ProjectReference Include="..\Core.Tests.Shared\Core.Tests.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="TestData\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
