<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <ProjectReference Include="..\Core.Json\Core.Json.csproj" />
      <ProjectReference Include="..\Core.Logger\Core.Logger.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Confluent.Kafka" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Options" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    </ItemGroup>

</Project>
