<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <ProjectReference Include="..\Core.BackgroundJobs\Core.BackgroundJobs.csproj" />
      <ProjectReference Include="..\Core.DateTimeProvider\Core.DateTimeProvider.csproj" />
      <ProjectReference Include="..\Core.DomainTypes\Core.DomainTypes.csproj" />
      <ProjectReference Include="..\Core.Infrastructure\Core.Infrastructure.csproj" />
      <ProjectReference Include="..\Core.Logger\Core.Logger.csproj" />
      <ProjectReference Include="..\Core.KafkaProducer\Core.KafkaProducer.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    </ItemGroup>

</Project>
